allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@vitest/expect@4.1.7'
  - '@vitest/mocker@4.1.7'
  - '@vitest/pretty-format@4.1.7'
  - '@vitest/runner@4.1.7'
  - '@vitest/snapshot@4.1.7'
  - '@vitest/spy@4.1.7'
  - '@vitest/utils@4.1.7'
  - echarts@6.1.0
  - vitest@4.1.7
  - '@myrmidon/cadmus-thesaurus-store@0.1.5'
  - '@myrmidon/paged-data-browsers@5.2.3'
  - '@myrmidon/auth-jwt-admin@9.0.0'
  - '@myrmidon/auth-jwt-login@9.0.0'
  - '@myrmidon/cadmus-mat-physical-size@10.0.0'
  - '@myrmidon/cadmus-mat-physical-state@10.0.0'
  - '@myrmidon/cadmus-refs-asserted-chronotope@12.0.0'
  - '@myrmidon/cadmus-refs-asserted-ids@11.0.0'
  - '@myrmidon/cadmus-refs-assertion@11.0.0'
  - '@myrmidon/cadmus-refs-biblissima-lookup@11.0.0'
  - '@myrmidon/cadmus-refs-citation@2.0.0'
  - '@myrmidon/cadmus-refs-decorated-counts@10.0.0'
  - '@myrmidon/cadmus-refs-doc-references@11.0.0'
  - '@myrmidon/cadmus-refs-geonames-lookup@11.0.0'
  - '@myrmidon/cadmus-refs-historical-date@10.0.0'
  - '@myrmidon/cadmus-refs-lookup@11.0.0'
  - '@myrmidon/cadmus-refs-proper-name@11.0.0'
  - '@myrmidon/cadmus-refs-viaf-lookup@11.0.0'
  - '@myrmidon/cadmus-text-block-view@10.0.0'
  - '@myrmidon/cadmus-text-ed-md@11.0.0'
  - '@myrmidon/cadmus-text-ed-txt@10.0.0'
  - '@myrmidon/cadmus-text-ed@10.0.0'
  - '@myrmidon/cadmus-thesaurus-store@1.0.0'
  - '@myrmidon/cadmus-ui-flag-set@10.0.0'
  - '@myrmidon/cadmus-ui-note-set@11.0.0'
  - '@myrmidon/ngx-mat-tools@2.0.0'
  - '@myrmidon/ngx-tools@3.0.0'
  - '@myrmidon/paged-data-browsers@6.0.0'
  - '@myrmidon/taxo-store-api@1.0.0'
  - '@myrmidon/taxo-store-editor@1.0.0'
  - '@myrmidon/taxo-store-picker@1.0.0'
